# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://sihangpu.uk"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Sihang Pu"
author = "SP"
copyright = "Sihang Pu."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[markup.goldmark.parser.attribute]
  block = true

[markup.highlight]
  style = 'dracula'

[params]
  scholar_url = "https://scholar.google.com/citations?user=lZqY8E0AAAAJ&hl=en"

  orcid_url = "https://orcid.org/0009-0003-2056-6079"

  dblp_url = "https://dblp.uni-trier.de/pid/195/8301"

  work_url = "https://cispa.de/en/people/sihang.pu"

  # This is used in the meta data of your generated html.
  description = ":heart:"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  ### Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.

  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.

  images = ["images/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.

  title = "Hugo ʕ•ᴥ•ʔ Bear"


  # Hide the footer or not

  hideMadeWithLine = false

  # By default, this theme displays dates with a format like "02 Jan, 2006", 
  # An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"
